### ISSUE TITLE
Installing and configuring Laravel

### ISSUE THREAD

**Issue by sirthxalot** [sta-laravel/mastering#1]
Lets start to build up the fundament (skeleton application), which is meant to be used as our starting point.

## Tasks 

- [x] Install Laravel 5.2 Skeleton Application
- [x] Add and setup Laravel Homestead
- [x] Add common project files
- [x] Change `App` namespace to `Acme`
- [x] Add [IDE Helper](https://github.com/barryvdh/laravel-ide-helper) Laravel Extension
- [x] Add [Generators](https://github.com/laracasts/Laravel-5-Generators-Extended) Laravel Extension
- [x] Add [Test Dummy](https://github.com/laracasts/TestDummy) Laravel Extension
